<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AisDataVesselsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('ais_data_vessels')->delete();
        
        \DB::table('ais_data_vessels')->insert(array (
            0 => 
            array (
                'id' => 1,
                'vessel_name' => NULL,
                'vessel_type' => NULL,
                'mmsi' => '525899371',
                'imo' => NULL,
                'callsign' => NULL,
                'draught' => NULL,
                'dimension_to_bow' => NULL,
                'dimension_to_stern' => NULL,
                'dimension_to_port' => NULL,
                'dimension_to_starboard' => NULL,
                'reported_destination' => NULL,
                'reported_eta' => NULL,
                'created_at' => '2023-05-26 07:43:55',
                'updated_at' => '2023-05-26 07:43:55',
            ),
            1 => 
            array (
                'id' => 2,
                'vessel_name' => NULL,
                'vessel_type' => NULL,
                'mmsi' => '525003500',
                'imo' => NULL,
                'callsign' => NULL,
                'draught' => NULL,
                'dimension_to_bow' => NULL,
                'dimension_to_stern' => NULL,
                'dimension_to_port' => NULL,
                'dimension_to_starboard' => NULL,
                'reported_destination' => NULL,
                'reported_eta' => NULL,
                'created_at' => '2023-05-26 07:43:55',
                'updated_at' => '2023-05-26 07:43:55',
            ),
            2 => 
            array (
                'id' => 3,
                'vessel_name' => NULL,
                'vessel_type' => NULL,
                'mmsi' => '525006403',
                'imo' => NULL,
                'callsign' => NULL,
                'draught' => NULL,
                'dimension_to_bow' => NULL,
                'dimension_to_stern' => NULL,
                'dimension_to_port' => NULL,
                'dimension_to_starboard' => NULL,
                'reported_destination' => NULL,
                'reported_eta' => NULL,
                'created_at' => '2023-05-26 07:43:55',
                'updated_at' => '2023-05-26 07:43:55',
            ),
            3 => 
            array (
                'id' => 4,
                'vessel_name' => NULL,
                'vessel_type' => NULL,
                'mmsi' => '525013016',
                'imo' => NULL,
                'callsign' => NULL,
                'draught' => NULL,
                'dimension_to_bow' => NULL,
                'dimension_to_stern' => NULL,
                'dimension_to_port' => NULL,
                'dimension_to_starboard' => NULL,
                'reported_destination' => NULL,
                'reported_eta' => NULL,
                'created_at' => '2023-05-26 07:43:56',
                'updated_at' => '2023-05-26 07:43:56',
            ),
            4 => 
            array (
                'id' => 5,
                'vessel_name' => NULL,
                'vessel_type' => NULL,
                'mmsi' => '525200515',
                'imo' => NULL,
                'callsign' => NULL,
                'draught' => NULL,
                'dimension_to_bow' => NULL,
                'dimension_to_stern' => NULL,
                'dimension_to_port' => NULL,
                'dimension_to_starboard' => NULL,
                'reported_destination' => NULL,
                'reported_eta' => NULL,
                'created_at' => '2023-05-26 07:43:57',
                'updated_at' => '2023-05-26 07:43:57',
            ),
            5 => 
            array (
                'id' => 6,
                'vessel_name' => NULL,
                'vessel_type' => NULL,
                'mmsi' => '525301105',
                'imo' => NULL,
                'callsign' => NULL,
                'draught' => NULL,
                'dimension_to_bow' => NULL,
                'dimension_to_stern' => NULL,
                'dimension_to_port' => NULL,
                'dimension_to_starboard' => NULL,
                'reported_destination' => NULL,
                'reported_eta' => NULL,
                'created_at' => '2023-05-26 07:43:58',
                'updated_at' => '2023-05-26 07:43:58',
            ),
            6 => 
            array (
                'id' => 7,
                'vessel_name' => NULL,
                'vessel_type' => NULL,
                'mmsi' => '525015921',
                'imo' => NULL,
                'callsign' => NULL,
                'draught' => NULL,
                'dimension_to_bow' => NULL,
                'dimension_to_stern' => NULL,
                'dimension_to_port' => NULL,
                'dimension_to_starboard' => NULL,
                'reported_destination' => NULL,
                'reported_eta' => NULL,
                'created_at' => '2023-05-26 07:43:58',
                'updated_at' => '2023-05-26 07:43:58',
            ),
            7 => 
            array (
                'id' => 8,
                'vessel_name' => NULL,
                'vessel_type' => NULL,
                'mmsi' => '525007280',
                'imo' => NULL,
                'callsign' => NULL,
                'draught' => NULL,
                'dimension_to_bow' => NULL,
                'dimension_to_stern' => NULL,
                'dimension_to_port' => NULL,
                'dimension_to_starboard' => NULL,
                'reported_destination' => NULL,
                'reported_eta' => NULL,
                'created_at' => '2023-05-26 07:43:59',
                'updated_at' => '2023-05-26 07:43:59',
            ),
            8 => 
            array (
                'id' => 9,
                'vessel_name' => NULL,
                'vessel_type' => NULL,
                'mmsi' => '257001155',
                'imo' => NULL,
                'callsign' => NULL,
                'draught' => NULL,
                'dimension_to_bow' => NULL,
                'dimension_to_stern' => NULL,
                'dimension_to_port' => NULL,
                'dimension_to_starboard' => NULL,
                'reported_destination' => NULL,
                'reported_eta' => NULL,
                'created_at' => '2023-05-26 07:44:01',
                'updated_at' => '2023-05-26 07:44:01',
            ),
            9 => 
            array (
                'id' => 10,
                'vessel_name' => NULL,
                'vessel_type' => NULL,
                'mmsi' => '215175000',
                'imo' => NULL,
                'callsign' => NULL,
                'draught' => NULL,
                'dimension_to_bow' => NULL,
                'dimension_to_stern' => NULL,
                'dimension_to_port' => NULL,
                'dimension_to_starboard' => NULL,
                'reported_destination' => NULL,
                'reported_eta' => NULL,
                'created_at' => '2023-05-26 07:44:06',
                'updated_at' => '2023-05-26 07:44:06',
            ),
            10 => 
            array (
                'id' => 11,
                'vessel_name' => NULL,
                'vessel_type' => NULL,
                'mmsi' => '525111222',
                'imo' => NULL,
                'callsign' => NULL,
                'draught' => NULL,
                'dimension_to_bow' => NULL,
                'dimension_to_stern' => NULL,
                'dimension_to_port' => NULL,
                'dimension_to_starboard' => NULL,
                'reported_destination' => NULL,
                'reported_eta' => NULL,
                'created_at' => '2023-05-26 07:44:08',
                'updated_at' => '2023-05-26 07:44:08',
            ),
            11 => 
            array (
                'id' => 12,
                'vessel_name' => NULL,
                'vessel_type' => NULL,
                'mmsi' => '525003693',
                'imo' => NULL,
                'callsign' => NULL,
                'draught' => NULL,
                'dimension_to_bow' => NULL,
                'dimension_to_stern' => NULL,
                'dimension_to_port' => NULL,
                'dimension_to_starboard' => NULL,
                'reported_destination' => NULL,
                'reported_eta' => NULL,
                'created_at' => '2023-05-26 07:44:09',
                'updated_at' => '2023-05-26 07:44:09',
            ),
            12 => 
            array (
                'id' => 13,
                'vessel_name' => NULL,
                'vessel_type' => NULL,
                'mmsi' => '525019090',
                'imo' => NULL,
                'callsign' => NULL,
                'draught' => NULL,
                'dimension_to_bow' => NULL,
                'dimension_to_stern' => NULL,
                'dimension_to_port' => NULL,
                'dimension_to_starboard' => NULL,
                'reported_destination' => NULL,
                'reported_eta' => NULL,
                'created_at' => '2023-05-26 07:44:10',
                'updated_at' => '2023-05-26 07:44:10',
            ),
            13 => 
            array (
                'id' => 14,
                'vessel_name' => NULL,
                'vessel_type' => NULL,
                'mmsi' => '525018039',
                'imo' => NULL,
                'callsign' => NULL,
                'draught' => NULL,
                'dimension_to_bow' => NULL,
                'dimension_to_stern' => NULL,
                'dimension_to_port' => NULL,
                'dimension_to_starboard' => NULL,
                'reported_destination' => NULL,
                'reported_eta' => NULL,
                'created_at' => '2023-05-26 07:44:14',
                'updated_at' => '2023-05-26 07:44:14',
            ),
            14 => 
            array (
                'id' => 15,
                'vessel_name' => NULL,
                'vessel_type' => NULL,
                'mmsi' => '525018038',
                'imo' => NULL,
                'callsign' => NULL,
                'draught' => NULL,
                'dimension_to_bow' => NULL,
                'dimension_to_stern' => NULL,
                'dimension_to_port' => NULL,
                'dimension_to_starboard' => NULL,
                'reported_destination' => NULL,
                'reported_eta' => NULL,
                'created_at' => '2023-05-26 07:44:14',
                'updated_at' => '2023-05-26 07:44:14',
            ),
            15 => 
            array (
                'id' => 16,
                'vessel_name' => NULL,
                'vessel_type' => NULL,
                'mmsi' => '525003095',
                'imo' => NULL,
                'callsign' => NULL,
                'draught' => NULL,
                'dimension_to_bow' => NULL,
                'dimension_to_stern' => NULL,
                'dimension_to_port' => NULL,
                'dimension_to_starboard' => NULL,
                'reported_destination' => NULL,
                'reported_eta' => NULL,
                'created_at' => '2023-05-26 07:44:22',
                'updated_at' => '2023-05-26 07:44:22',
            ),
            16 => 
            array (
                'id' => 17,
                'vessel_name' => NULL,
                'vessel_type' => NULL,
                'mmsi' => '636021991',
                'imo' => NULL,
                'callsign' => NULL,
                'draught' => NULL,
                'dimension_to_bow' => NULL,
                'dimension_to_stern' => NULL,
                'dimension_to_port' => NULL,
                'dimension_to_starboard' => NULL,
                'reported_destination' => NULL,
                'reported_eta' => NULL,
                'created_at' => '2023-05-26 07:44:25',
                'updated_at' => '2023-05-26 07:44:25',
            ),
            17 => 
            array (
                'id' => 18,
                'vessel_name' => NULL,
                'vessel_type' => NULL,
                'mmsi' => '545392672',
                'imo' => NULL,
                'callsign' => NULL,
                'draught' => NULL,
                'dimension_to_bow' => NULL,
                'dimension_to_stern' => NULL,
                'dimension_to_port' => NULL,
                'dimension_to_starboard' => NULL,
                'reported_destination' => NULL,
                'reported_eta' => NULL,
                'created_at' => '2023-05-26 07:44:30',
                'updated_at' => '2023-05-26 07:44:30',
            ),
            18 => 
            array (
                'id' => 19,
                'vessel_name' => NULL,
                'vessel_type' => NULL,
                'mmsi' => '525005227',
                'imo' => NULL,
                'callsign' => NULL,
                'draught' => NULL,
                'dimension_to_bow' => NULL,
                'dimension_to_stern' => NULL,
                'dimension_to_port' => NULL,
                'dimension_to_starboard' => NULL,
                'reported_destination' => NULL,
                'reported_eta' => NULL,
                'created_at' => '2023-05-26 07:44:32',
                'updated_at' => '2023-05-26 07:44:32',
            ),
            19 => 
            array (
                'id' => 20,
                'vessel_name' => NULL,
                'vessel_type' => NULL,
                'mmsi' => '533170709',
                'imo' => NULL,
                'callsign' => NULL,
                'draught' => NULL,
                'dimension_to_bow' => NULL,
                'dimension_to_stern' => NULL,
                'dimension_to_port' => NULL,
                'dimension_to_starboard' => NULL,
                'reported_destination' => NULL,
                'reported_eta' => NULL,
                'created_at' => '2023-05-26 07:44:38',
                'updated_at' => '2023-05-26 07:44:38',
            ),
            20 => 
            array (
                'id' => 21,
                'vessel_name' => NULL,
                'vessel_type' => NULL,
                'mmsi' => '352927000',
                'imo' => NULL,
                'callsign' => NULL,
                'draught' => NULL,
                'dimension_to_bow' => NULL,
                'dimension_to_stern' => NULL,
                'dimension_to_port' => NULL,
                'dimension_to_starboard' => NULL,
                'reported_destination' => NULL,
                'reported_eta' => NULL,
                'created_at' => '2023-05-26 07:44:41',
                'updated_at' => '2023-05-26 07:44:41',
            ),
            21 => 
            array (
                'id' => 22,
                'vessel_name' => NULL,
                'vessel_type' => NULL,
                'mmsi' => '000000000',
                'imo' => NULL,
                'callsign' => NULL,
                'draught' => NULL,
                'dimension_to_bow' => NULL,
                'dimension_to_stern' => NULL,
                'dimension_to_port' => NULL,
                'dimension_to_starboard' => NULL,
                'reported_destination' => NULL,
                'reported_eta' => '2023-05-26 07:46:06',
                'created_at' => '2023-05-26 07:44:47',
                'updated_at' => '2023-05-26 07:46:06',
            ),
            22 => 
            array (
                'id' => 23,
                'vessel_name' => NULL,
                'vessel_type' => NULL,
                'mmsi' => '525201201',
                'imo' => NULL,
                'callsign' => NULL,
                'draught' => NULL,
                'dimension_to_bow' => NULL,
                'dimension_to_stern' => NULL,
                'dimension_to_port' => NULL,
                'dimension_to_starboard' => NULL,
                'reported_destination' => NULL,
                'reported_eta' => NULL,
                'created_at' => '2023-05-26 07:45:02',
                'updated_at' => '2023-05-26 07:45:02',
            ),
            23 => 
            array (
                'id' => 24,
                'vessel_name' => NULL,
                'vessel_type' => NULL,
                'mmsi' => '525208005',
                'imo' => NULL,
                'callsign' => NULL,
                'draught' => NULL,
                'dimension_to_bow' => NULL,
                'dimension_to_stern' => NULL,
                'dimension_to_port' => NULL,
                'dimension_to_starboard' => NULL,
                'reported_destination' => NULL,
                'reported_eta' => NULL,
                'created_at' => '2023-05-26 07:45:06',
                'updated_at' => '2023-05-26 07:45:06',
            ),
            24 => 
            array (
                'id' => 25,
                'vessel_name' => NULL,
                'vessel_type' => NULL,
                'mmsi' => '636022155',
                'imo' => NULL,
                'callsign' => NULL,
                'draught' => NULL,
                'dimension_to_bow' => NULL,
                'dimension_to_stern' => NULL,
                'dimension_to_port' => NULL,
                'dimension_to_starboard' => NULL,
                'reported_destination' => NULL,
                'reported_eta' => NULL,
                'created_at' => '2023-05-26 07:45:11',
                'updated_at' => '2023-05-26 07:45:11',
            ),
            25 => 
            array (
                'id' => 26,
                'vessel_name' => NULL,
                'vessel_type' => NULL,
                'mmsi' => '525001247',
                'imo' => NULL,
                'callsign' => NULL,
                'draught' => NULL,
                'dimension_to_bow' => NULL,
                'dimension_to_stern' => NULL,
                'dimension_to_port' => NULL,
                'dimension_to_starboard' => NULL,
                'reported_destination' => NULL,
                'reported_eta' => NULL,
                'created_at' => '2023-05-26 07:45:18',
                'updated_at' => '2023-05-26 07:45:18',
            ),
            26 => 
            array (
                'id' => 27,
                'vessel_name' => NULL,
                'vessel_type' => NULL,
                'mmsi' => '477144700',
                'imo' => NULL,
                'callsign' => NULL,
                'draught' => NULL,
                'dimension_to_bow' => NULL,
                'dimension_to_stern' => NULL,
                'dimension_to_port' => NULL,
                'dimension_to_starboard' => NULL,
                'reported_destination' => NULL,
                'reported_eta' => NULL,
                'created_at' => '2023-05-26 07:45:21',
                'updated_at' => '2023-05-26 07:45:21',
            ),
            27 => 
            array (
                'id' => 28,
                'vessel_name' => NULL,
                'vessel_type' => NULL,
                'mmsi' => '477855200',
                'imo' => NULL,
                'callsign' => NULL,
                'draught' => NULL,
                'dimension_to_bow' => NULL,
                'dimension_to_stern' => NULL,
                'dimension_to_port' => NULL,
                'dimension_to_starboard' => NULL,
                'reported_destination' => NULL,
                'reported_eta' => NULL,
                'created_at' => '2023-05-26 07:45:25',
                'updated_at' => '2023-05-26 07:45:25',
            ),
            28 => 
            array (
                'id' => 29,
                'vessel_name' => NULL,
                'vessel_type' => NULL,
                'mmsi' => '525015954',
                'imo' => NULL,
                'callsign' => NULL,
                'draught' => NULL,
                'dimension_to_bow' => NULL,
                'dimension_to_stern' => NULL,
                'dimension_to_port' => NULL,
                'dimension_to_starboard' => NULL,
                'reported_destination' => NULL,
                'reported_eta' => NULL,
                'created_at' => '2023-05-26 07:45:32',
                'updated_at' => '2023-05-26 07:45:32',
            ),
            29 => 
            array (
                'id' => 30,
                'vessel_name' => NULL,
                'vessel_type' => NULL,
                'mmsi' => '525900926',
                'imo' => NULL,
                'callsign' => NULL,
                'draught' => NULL,
                'dimension_to_bow' => NULL,
                'dimension_to_stern' => NULL,
                'dimension_to_port' => NULL,
                'dimension_to_starboard' => NULL,
                'reported_destination' => NULL,
                'reported_eta' => NULL,
                'created_at' => '2023-05-26 07:45:42',
                'updated_at' => '2023-05-26 07:45:42',
            ),
            30 => 
            array (
                'id' => 31,
                'vessel_name' => NULL,
                'vessel_type' => NULL,
                'mmsi' => '525201202',
                'imo' => NULL,
                'callsign' => NULL,
                'draught' => NULL,
                'dimension_to_bow' => NULL,
                'dimension_to_stern' => NULL,
                'dimension_to_port' => NULL,
                'dimension_to_starboard' => NULL,
                'reported_destination' => NULL,
                'reported_eta' => NULL,
                'created_at' => '2023-05-26 07:45:59',
                'updated_at' => '2023-05-26 07:45:59',
            ),
        ));
        
        
    }
}