<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class DataBUP extends Model
{
    public $table = 'data_bups';

    public $fillable = [
        'id_rkbm',
        'ais_data_vessel_id',
        'pbm_kode',
        'no_pkk',
        'no_surat_keluar',
        'kade',
        'rencana_bongkar',
        'rencana_muat',
        'mulai_bongkar',
        'mulai_muat',
        'actual_mulai_bongkar',
        'actual_mulai_muat',
        'selesai_bongkar',
        'selesai_muat',
        'actual_selesai_bongkar',
        'actual_selesai_muat',
        'nomor_layanan_masuk',
        'nomor_layanan_sps',
        'nama_kapal',
        'gt_kapal',
        'panjang_kapal',
        'dwt',
        'siupal_pemilik',
        'siupal_operator',
        'bendera',
        'nama_perusahaan',
        'nomor_produk',
        'tipe_kapal',
        'pbm',
        'bongkar',
        'muat',
        'image_mulai',
        'image_sedang',
        'image_selesai',
        'image_mulai_2',
        'image_sedang_2',
        'image_selesai_2',
        'image_mulai_3',
        'image_sedang_3',
        'image_selesai_3',
        'no_pkk_assign',
        'mmsi',
        'jenis_layanan',
        'nama_negara',
        'tgl_tiba',
        'tgl_brangkat',
        'no_imo',
        'call_sign',
        'nakhoda',
        'jenis_trayek',
        'pelabuhan_asal',
        'pelabuhan_tujuan',
        'lokasi_lambat_labuh',
        'waktu_respon',
        'nomor_spog',
        'no_pandu',
        'nama_pandu',
        'grt',
        'loa',
        'tanggal_pandu_naik_kapal',
        'tanggal_pandu_turun_kapal',
        'jam_pandu_naik_kapal',
        'jam_pandu_turun_kapal',
        'biaya_layanan',
        'jumlah_pnbp',
        'foto_di_kapal',
        'bpjp'
    ];

    protected $casts = [
        'pbm_kode' => 'string',
        'no_pkk' => 'string',
        'no_surat_keluar' => 'string',
        'kade' => 'string',
        'rencana_bongkar' => 'date',
        'rencana_muat' => 'date',
        'mulai_bongkar' => 'date',
        'mulai_muat' => 'date',
        'actual_mulai_bongkar' => 'datetime',
        'actual_mulai_muat' => 'datetime',
        'selesai_bongkar' => 'date',
        'selesai_muat' => 'date',
        'actual_selesai_bongkar' => 'datetime',
        'actual_selesai_muat' => 'datetime',
        'nomor_layanan_masuk' => 'string',
        'nomor_layanan_sps' => 'string',
        'nama_kapal' => 'string',
        'siupal_pemilik' => 'string',
        'siupal_operator' => 'string',
        'bendera' => 'string',
        'nama_perusahaan' => 'string',
        'nomor_produk' => 'string',
        'tipe_kapal' => 'string',
        'pbm' => 'string',
        'bongkar' => 'string',
        'muat' => 'string',
        'image_mulai' => 'string',
        'image_sedang' => 'string',
        'image_selesai' => 'string',
        'image_mulai_2' => 'string',
        'image_sedang_2' => 'string',
        'image_selesai_2' => 'string',
        'image_mulai_3' => 'string',
        'image_sedang_3' => 'string',
        'image_selesai_3' => 'string',
        'no_pkk_assign' => 'string',
        'mmsi' => 'string',
        'jenis_layanan' => 'string',
        'nama_negara' => 'string',
        'tgl_tiba' => 'datetime',
        'tgl_brangkat' => 'datetime',
        'no_imo' => 'string',
        'call_sign' => 'string',
        'nakhoda' => 'string',
        'jenis_trayek' => 'string',
        'pelabuhan_asal' => 'string',
        'pelabuhan_tujuan' => 'string',
        'lokasi_lambat_labuh' => 'string',
        'waktu_respon' => 'string',
        'nomor_spog' => 'string',
        'no_pandu' => 'string',
        'nama_pandu' => 'string',
        'tanggal_pandu_naik_kapal' => 'date',
        'tanggal_pandu_turun_kapal' => 'date',
        'foto_di_kapal' => 'string',
        'bpjp' => 'string'
    ];

    public static array $rules = [
        'id_rkbm' => 'nullable',
        'ais_data_vessel_id' => 'nullable',
        'pbm_kode' => 'nullable|string|max:255',
        'no_pkk' => 'nullable|string|max:255',
        'no_surat_keluar' => 'nullable|string|max:255',
        'kade' => 'nullable|string|max:255',
        'rencana_bongkar' => 'nullable',
        'rencana_muat' => 'nullable',
        'mulai_bongkar' => 'nullable',
        'mulai_muat' => 'nullable',
        'actual_mulai_bongkar' => 'nullable',
        'actual_mulai_muat' => 'nullable',
        'selesai_bongkar' => 'nullable',
        'selesai_muat' => 'nullable',
        'actual_selesai_bongkar' => 'nullable',
        'actual_selesai_muat' => 'nullable',
        'nomor_layanan_masuk' => 'nullable|string|max:255',
        'nomor_layanan_sps' => 'nullable|string|max:255',
        'nama_kapal' => 'nullable|string|max:255',
        'gt_kapal' => 'nullable',
        'panjang_kapal' => 'nullable',
        'dwt' => 'nullable',
        'siupal_pemilik' => 'nullable|string|max:255',
        'siupal_operator' => 'nullable|string|max:255',
        'bendera' => 'nullable|string|max:255',
        'nama_perusahaan' => 'nullable|string|max:255',
        'nomor_produk' => 'nullable|string|max:255',
        'tipe_kapal' => 'nullable|string|max:255',
        'pbm' => 'nullable|string|max:255',
        'bongkar' => 'nullable|string',
        'muat' => 'nullable|string',
        'image_mulai' => 'nullable|string',
        'image_sedang' => 'nullable|string',
        'image_selesai' => 'nullable|string',
        'image_mulai_2' => 'nullable|string',
        'image_sedang_2' => 'nullable|string',
        'image_selesai_2' => 'nullable|string',
        'image_mulai_3' => 'nullable|string',
        'image_sedang_3' => 'nullable|string',
        'image_selesai_3' => 'nullable|string',
        'no_pkk_assign' => 'nullable|string|max:255',
        'mmsi' => 'nullable|string|max:255',
        'jenis_layanan' => 'nullable|string|max:255',
        'nama_negara' => 'nullable|string|max:255',
        'tgl_tiba' => 'nullable',
        'tgl_brangkat' => 'nullable',
        'no_imo' => 'nullable|string|max:255',
        'call_sign' => 'nullable|string|max:255',
        'nakhoda' => 'nullable|string|max:255',
        'jenis_trayek' => 'nullable|string|max:255',
        'pelabuhan_asal' => 'nullable|string|max:255',
        'pelabuhan_tujuan' => 'nullable|string|max:255',
        'lokasi_lambat_labuh' => 'nullable|string|max:255',
        'waktu_respon' => 'nullable|string|max:255',
        'nomor_spog' => 'nullable|string|max:255',
        'no_pandu' => 'nullable|string|max:255',
        'nama_pandu' => 'nullable|string|max:255',
        'grt' => 'nullable',
        'loa' => 'nullable',
        'tanggal_pandu_naik_kapal' => 'nullable',
        'tanggal_pandu_turun_kapal' => 'nullable',
        'jam_pandu_naik_kapal' => 'nullable',
        'jam_pandu_turun_kapal' => 'nullable',
        'biaya_layanan' => 'nullable',
        'jumlah_pnbp' => 'nullable',
        'foto_di_kapal' => 'nullable|string|max:255',
        'bpjp' => 'nullable|string|max:255',
        'created_at' => 'nullable',
        'updated_at' => 'nullable'
    ];

    
}
